runmode: debug               # 开发模式, debug, release, test
addr: :8080                  # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://localhost:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10

log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: false
  rollingPolicy: daily
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7

db:
  name: gorestful
  addr: 127.0.0.1:3306
  username: gorestful
  password: ash12312
docker_db:
  name: gorestful
  addr: 127.0.0.1:3306
  username: gorestful
  password: ash12312